apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: labpulse
  namespace: labpulse
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: labpulse
                port:
                  number: 5000
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: labpulse
                port:
                  number: 5000
